In [1]:
import pandas as pd
from datetime import datetime
import re

In [ ]:
df = pd.read_json("../data/raw/hasil_tokopedia_scrap.json")
print("Jumlah data mentah: ", len(df))
df.head()

Jumlah data mentah:  300

,Nama,Harga,Rating,Toko,Lokasi,URL
0,Rexus S9 Pro Headphone Bluetooth with ANC Head...,Rp468.210,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/rexus-s9-...
1,Headset / Headphone Gaming Rexus S6 / S 6 Pro ...,Rp425.000,5.0,BintangRayaKomputer,Jakarta Pusat,https://www.tokopedia.com/bintangrayacom/heads...
2,Fantech Go Move WH03 Wireless Bluetooth Headse...,Rp250.850,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/fantech-g...
3,Fantech WH05 GO VIBE Headset Wireless Bluetoot...,Rp212.370,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/fantech-w...
4,Olike T102 TWS Bluetooth Earphone True Wireles...,Rp125.010,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/olike-t10...

In [3]:
df.info()
df.describe(include='all')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Nama    300 non-null    object
 1   Harga   300 non-null    object
 2   Rating  300 non-null    float64
 3   Toko    300 non-null    object
 4   Lokasi  300 non-null    object
 5   URL     300 non-null    object
dtypes: float64(1), object(5)
memory usage: 14.2+ KB

,Nama,Harga,Rating,Toko,Lokasi,URL
count,300,300,300.000000,300,300,300
unique,114,104,NaN,72,16,300
top,Headphone Bluetooth Soundcore H30i - A3012,Rp399.000,NaN,Click & Go Tokopedia,Jakarta Pusat,https://www.tokopedia.com/clickandgo/rexus-s9-...
freq,9,15,NaN,29,67,1
mean,NaN,NaN,4.975667,NaN,NaN,NaN
std,NaN,NaN,0.060994,NaN,NaN,NaN
min,NaN,NaN,4.700000,NaN,NaN,NaN
25%,NaN,NaN,5.000000,NaN,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN,NaN
75%,NaN,NaN,5.000000,NaN,NaN,NaN
max,NaN,NaN,5.000000,NaN,NaN,NaN

In [4]:
df.columns = ['nama_produk', 'harga', 'rating', 'nama_toko', 'lokasi_toko', 'url']

In [5]:
df.head(1)

,nama_produk,harga,rating,nama_toko,lokasi_toko,url
0,Rexus S9 Pro Headphone Bluetooth with ANC Head...,Rp468.210,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/rexus-s9-...

In [6]:
def clean_price(harga):
    if isinstance(harga, str):
        harga = re.sub(r'[^0-9]', '', harga)
        return int(harga) if harga else None
    return None

In [7]:
df['harga'] = df['harga'].apply(clean_price)

In [9]:
df.head()

,nama_produk,harga,rating,nama_toko,lokasi_toko,url
0,Rexus S9 Pro Headphone Bluetooth with ANC Head...,468210,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/rexus-s9-...
1,Headset / Headphone Gaming Rexus S6 / S 6 Pro ...,425000,5.0,BintangRayaKomputer,Jakarta Pusat,https://www.tokopedia.com/bintangrayacom/heads...
2,Fantech Go Move WH03 Wireless Bluetooth Headse...,250850,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/fantech-g...
3,Fantech WH05 GO VIBE Headset Wireless Bluetoot...,212370,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/fantech-w...
4,Olike T102 TWS Bluetooth Earphone True Wireles...,125010,5.0,Click & Go Tokopedia,Bandung,https://www.tokopedia.com/clickandgo/olike-t10...

In [13]:
before = len(df)
df = df.drop_duplicates(subset=['nama_produk', 'nama_toko'])
after = len(df)
print(f"Duplikat dihapus: {before - after} baris")

Duplikat dihapus: 180 baris

In [15]:
df['timestamp_cleaned'] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

In [16]:
df = df.sort_values(by='harga', ascending=True).reset_index(drop=True)

In [ ]:
output_path = "../data/cleaned/tokopedia_headphone_cleaned.csv"
df.to_csv(output_path, index=False)
print(f"Data bersih disimpan ke {output_path}")

Data bersih disimpan ke data/cleaned/tokopedia_headphone_cleaned.csv

In [19]:
df.head()

,nama_produk,harga,rating,nama_toko,lokasi_toko,url,timestamp_cleaned
0,MIISOO Karet Pengikat Earphone TWS Bluetooth H...,10000,4.7,MIISOO,Kab. Tangerang,https://www.tokopedia.com/miisooid/miisoo-kare...,2025-10-25 07:07:46
1,AMINO EP05 Headset 3.5mm Jack / Wired Headset ...,22900,4.8,AMINO Shop Indonesia,Jakarta Barat,https://www.tokopedia.com/aminoofficialstore/a...,2025-10-25 07:07:46
2,AVEN Headphone Bluetooth P47 Headset Bando V5....,28056,4.8,Aven Indonesia,Jakarta Barat,https://www.tokopedia.com/avenindonesia/aven-h...,2025-10-25 07:07:46
3,AVEN Headphone Bluetooth MZ-023 Led Telinga Ku...,48337,5.0,Aven Indonesia,Jakarta Barat,https://www.tokopedia.com/avenindonesia/aven-h...,2025-10-25 07:07:46
4,Izzy X Km KL38 Bluetooth Headset Headphone Ear...,62269,5.0,Izzy Audio,Jakarta Pusat,https://www.tokopedia.com/izzy-audio/izzy-x-km...,2025-10-25 07:07:46